[ray.init]


[[job]]
num_cpus = 1
#num_gpus = 0
#resources = {res1=1}
cmd="examples/sample.py -t \"test test\" 'aa ' -c"


[[job]]
num_cpus = 0.1
cmd="examples/sample.py -t1 -d"
[job.runtime_env]
env_vars={DEBUG="1", TRACE="True"}